[env]
term = "xterm-256color"

[scrolling]
history = 5000

[font]
size = 11
normal = {family = "JetBrains Mono", style = "Regular"}

[terminal.shell]
program = "/usr/bin/zsh"  # Path to the Zsh binary (adjust if necessary)
args = ["--login"]


# Cursor settings

# [colors.primary]
# background = '#1a1b26'
# foreground = '#a9b1d6'

# tokyo night
# Normal colors
# [colors.normal]
# black   = '#32344a'
# red     = '#f7768e'
# green   = '#9ece6a'
# yellow  = '#e0af68'
# blue    = '#7aa2f7'
# magenta = '#ad8ee6'
# cyan    = '#449dab'
# white   = '#787c99'
#
# # Bright colors
# [colors.bright]
# black   = '#444b6a'
# red     = '#ff7a93'
# green   = '#b9f27c'
# yellow  = '#ff9e64'
# blue    = '#7da6ff'
# magenta = '#bb9af7'
# cyan    = '#0db9d7'
# white   = '#acb0d0'

# [colors.primary]
# background = "#1e1e2e"
# foreground = "#cdd6f4"
# dim_foreground = "#7f849c"
# bright_foreground = "#cdd6f4"
#
# [colors.cursor]
# text = "#1e1e2e"
# cursor = "#f5e0dc"
#
# [colors.vi_mode_cursor]
# text = "#1e1e2e"
# cursor = "#b4befe"
#
# [colors.search.matches]
# foreground = "#1e1e2e"
# background = "#a6adc8"
#
# [colors.search.focused_match]
# foreground = "#1e1e2e"
# background = "#a6e3a1"
#
# [colors.footer_bar]
# foreground = "#1e1e2e"
# background = "#a6adc8"
#
# [colors.hints.start]
# foreground = "#1e1e2e"
# background = "#f9e2af"
#
# [colors.hints.end]
# foreground = "#1e1e2e"
# background = "#a6adc8"
#
# [colors.selection]
# text = "#1e1e2e"
# background = "#f5e0dc"
#
# [colors.normal]
# black = "#45475a"
# red = "#f38ba8"
# green = "#a6e3a1"
# yellow = "#f9e2af"
# blue = "#89b4fa"
# magenta = "#f5c2e7"
# cyan = "#94e2d5"
# white = "#bac2de"
#
# [colors.bright]
# black = "#585b70"
# red = "#f38ba8"
# green = "#a6e3a1"
# yellow = "#f9e2af"
# blue = "#89b4fa"
# magenta = "#f5c2e7"
# cyan = "#94e2d5"
# white = "#a6adc8"
#
# [[colors.indexed_colors]]
# index = 16
# color = "#fab387"
#
# [[colors.indexed_colors]]
# index = 17
# color = "#f5e0dc"

# [colors.primary]
# background = '#1E1E2E' # base
# foreground = '#CDD6F4' # text
# # Bright and dim foreground colors
# dim_foreground = '#CDD6F4' # text
# bright_foreground = '#CDD6F4' # text

# # Cursor colors
# [colors.cursor]
# text = '#1E1E2E' # base
# cursor = '#F5E0DC' # rosewater

# [colors.vi_mode_cursor]
# text = '#1E1E2E' # base
# cursor = '#B4BEFE' # lavender

# # Search colors
# [colors.search.matches]
# foreground = '#1E1E2E' # base
# background = '#A6ADC8' # subtext0

# [colors.search.focused_match]
# foreground = '#1E1E2E' # base
# background = '#A6E3A1' # green

# [colors.footer_bar]
# foreground = '#1E1E2E' # base
# background = '#A6ADC8' # subtext0

# # Keyboard regex hints
# [colors.hints.start]
# foreground = '#1E1E2E' # base
# background = '#F9E2AF' # yellow

# [colors.hints.end]
# foreground = '#1E1E2E' # base
# background = '#A6ADC8' # subtext0

# # Selection colors
# [colors.selection]
# text = '#1E1E2E' # base
# background = '#F5E0DC' # rosewater

# # Normal colors
# [colors.normal]
# black = '#45475A' # surface1
# red = '#F38BA8' # red
# green = '#A6E3A1' # green
# yellow = '#F9E2AF' # yellow
# blue = '#89B4FA' # blue
# magenta = '#F5C2E7' # pink
# cyan = '#94E2D5' # teal
# white = '#BAC2DE' # subtext1

# # Bright colors
# [colors.bright]
# black = '#585B70' # surface2
# red = '#F38BA8' # red
# green = '#A6E3A1' # green
# yellow = '#F9E2AF' # yellow
# blue = '#89B4FA' # blue
# magenta = '#F5C2E7' # pink
# cyan = '#94E2D5' # teal
# white = '#A6ADC8' # subtext0

# # Dim colors
# [colors.dim]
# black = '#45475A' # surface1
# red = '#F38BA8' # red
# green = '#A6E3A1' # green
# yellow = '#F9E2AF' # yellow
# blue = '#89B4FA' # blue
# magenta = '#F5C2E7' # pink
# cyan = '#94E2D5' # teal
# white = '#BAC2DE' # subtext1

# Kanagawa Alacritty Colors
[colors]
  [colors.primary]
    background = "0x1f1e2e"
    foreground = "0xdcd7ba"

  [colors.normal]
    black   = "0x090618"
    red     = "0xc34043"
    green   = "0x76946a"
    yellow  = "0xc0a36e"
    blue    = "0x7e9cd8"
    magenta = "0x957fb8"
    cyan    = "0x6a9589"
    white   = "0xc8c093"

  [colors.bright]
    black   = "0x727169"
    red     = "0xe82424"
    green   = "0x98bb6c"
    yellow  = "0xe6c384"
    blue    = "0x7fb4ca"
    magenta = "0x938aa9"
    cyan    = "0x7aa89f"
    white   = "0xdcd7ba"

  [colors.selection]
    background = "0x2d4f67"
    foreground = "0xc8c093"

  [[colors.indexed_colors]]
    index = 16
    color = "0xffa066"

  [[colors.indexed_colors]]
    index = 17
    color = "0xff5d62"

[terminal]





