require("ash.plugins")
require("ash.settings")
require("ash.remap")
require("ash.treesitter")
require("ash.telescope")
require("ash.lsp")
require("ash.oil")
require("ash.autopairs")
require("ash.leap")
require("ash.conform")

require("lspconfig").csharp_ls.setup({})
require("lspconfig").css_variables.setup({})
